### PR TITLE
TLS support

### PR DESCRIPTION
**Pull request by streamnsight**
added flags and transport config.TLS object to connect to backend store secured with TLS

### CODE REVIEW

**Comment by darkcrux** [comment]
lgtm :)

**Comment by streamnsight** [comment]
Thanks

**Comment by streamnsight** [comment]
@darkcrux 
not sure how you cut a new release, but the PR didn't trigger one...

**Comment by darkcrux** [comment]
Hi @streamnsight, I'll make a release today. will let you know asap.

**Comment by darkcrux** [comment]
release v0.0.7 is out now: https://github.com/AcalephStorage/kviator/releases/tag/v0.0.7

**Comment by streamnsight** [comment]
👍

**Pull request merged**
